version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:05"
      timezone: "Europe/Amsterdam"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "00:05"
      timezone: "Europe/Amsterdam"
