# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  PACKAGES: [
    cliimage,
    goserv,
  ]

tasks:
  install:tools:
    desc: Install all tools needed
    cmds:
      - go install mvdan.cc/gofumpt@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

  fmt:
    desc: Run gofumpt for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && $HOME/go/bin/gofumpt -w .

  modernize:
    desc: Run modernize for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && $HOME/go/bin/modernize -fix ./...
  
  lint:
    desc: Run base linters for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && $HOME/go/bin/golangci-lint run
  
  lint:fix:
    desc: Run base linters and fix issues for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && $HOME/go/bin/golangci-lint run --fix
  
  test:
    desc: Run tests for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && go test ./...

  tidy:
    desc: Run `go mod tidy` for all packages
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && go mod tidy
  
  build:
    desc: Build all binaries
    cmds:
      - rm -rf ./bin && mkdir ./bin
      - cd cliimage && go build -o ../bin/cliimage .
      - cd goserv && go build -o ../bin/goserv .
