package models

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

var (
	publicKeyRootPath string
	tmplPublicKey     = "### autogenerated by gitserver. DO NOT EDIT\n" +
		"command=\"gitserver-serve %s\",no-port-forwarding," +
		"no-X11-forwarding,no-agent-forwarding,no-pty %s"
)

type PublicKey struct {
	Id      int64     `gorm:"primaryKey"`
	OwnerId int64     `gorm:"index"`
	Name    string    `gorm:"uniqueIndex;not null"`
	Content string    `gorm:"type:text;not null"`
	Created time.Time `gorm:"autoCreateTime"`
	Updated time.Time `gorm:"autoUpdateTime"`
}

func (PublicKey) TableName() string {
	return "public_key"
}

func init() {
	publicKeyRootPath = "/home/git/.ssh"
	if err := os.MkdirAll(publicKeyRootPath, 0700); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create public key root path: %v\n", err)
	}
}

func GenAuthorizedKey(user, key string) string {
	return fmt.Sprintf(tmplPublicKey, user, key)
}

func AddPublicKey(key *PublicKey, user string) error {
	if err := DB.Create(key).Error; err != nil {
		return err
	}

	if err := SaveAuthorizedKeyFile(user, key.Content); err != nil {
		DB.Delete(key)
		return err
	}

	return nil
}

func SaveAuthorizedKeyFile(user, key string) error {
	f, err := os.Create(filepath.Join(publicKeyRootPath, user+".pub"))
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(GenAuthorizedKey(user, key))
	return err
}
