name: Go

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.3.0
        with:
          go-version: '1.25.7'
          cache: true
      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            $/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Taskfile.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Install all tools needed
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          $HOME/go/bin/task install:tools

  gofumpt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.3.0
        with:
          go-version: '1.25.7'
          cache: true
      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            $/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Taskfile.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Run gofumpt
        run: $HOME/go/bin/task fmt

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.3.0
        with:
          go-version: '1.25.7'
          cache: true
      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            $/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Taskfile.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Run linter
        run: $HOME/go/bin/task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.3.0
        with:
          go-version: '1.25.7'
          cache: true
      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            $/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Taskfile.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Run tests
        run: $HOME/go/bin/task test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6.3.0
        with:
          go-version: '1.25.7'
          cache: true
      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            $/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Taskfile.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-
      - name: Build binaries
        run: $HOME/go/bin/task build
