name: Reviewbot

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  manual_invocation:
    if: |
      startsWith(github.event.comment.body, '/goreviewer')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version: stable
      - name: Run goreviewer
        run: |
          go run ./goreviewer/ -- review --post --model "stepfun/step-3.5-flash:free" --pr ${{ env.PR_NUMBER }} --repo ${{ env.REPO_FULL_NAME }}
        env:
          PR_NUMBER: "${{ github.event.pull_request.number }}"
          REPO_FULL_NAME: "${{ github.repository }}"
